### ISSUE TITLE
Tweets are protected

### ISSUE THREAD

**Issue by alistair-broomhead** [for-GET/know-your-http-well#42]
Many of the links in the Status entry are to protected tweets, and therefore inaccessible to the general viewing public

**Comment by andreineculau** [comment]
Not my twitter account, nor does the tweet contains more info than what it's present in this repo.

For reference, a copy from [here](http://instanceof.me/post/19918944485/http-response-codes-for-dummies):

> "HTTP response codes for dummies. 50x: we fucked up. 40x: you fucked up. 30x: ask that dude over there. 20x: cool."
> — Dana Contreras

Please file a PR if you have something in mind. Thank you.
