### ISSUE TITLE
Missing status codes 408 & 418

### ISSUE THREAD

**Issue by imaustink** [for-GET/know-your-http-well#45]
The [RFC](http://tools.ietf.org/html/rfc2324#section-2.3.2) might be a joke but it's typically supported by most libraries pertaining to HTTP.

**Comment by imaustink** [comment]
[Pull request](https://github.com/for-GET/know-your-http-well/pull/46)

**Comment by dret** [comment]
On 2016-01-30 19:32, Austin Kurpuis wrote:
> The RFC <http://tools.ietf.org/html/rfc2324#section-2.3.2> might be a
> joke but it's typically supported by most libraries pertaining to HTTP.

the title suggests 408 and 418 are added, the PR adds 406/418/422.

the IANA registry already lists 406 and 422 as defined by other RFCs, 
and lists just 418 as "Unassgined". if the PR is accepted, i suggest to 
trim it down to only contain 418.
