### ISSUE TITLE
add Emacs version to MELPA

### ISSUE THREAD

**Issue by jasonm23** [for-GET/know-your-http-well#47]

**Comment by jasonm23** [comment]
I am dumb, I see it's already there.

**Comment by andreineculau** [comment]
No problem :)

On the topic of the emacs package, there is one thing that I didn't open an
issue for, and that is printing the links, in addition to the
header/status/etc. short explanation. If you want to do this improvement
(which means just changing an emacs file and a coffeescript one in the
generator branch), I'd happily take in a PR.

On Mon, May 30, 2016 at 8:22 AM, JasonM23 <notifications@github.com> wrote:

> Closed #47 <https://github.com/for-GET/know-your-http-well/issues/47>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/for-GET/know-your-http-well/issues/47#event-675683430>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AArOQWvcphWgfSKlq3gosVQDMBfhWzGmks5qGoIsgaJpZM4Ipeuy>
> .
>



-- 
andreineculau.com <http://www.andreineculau.com>
