### ISSUE TITLE
Add JSON representation to make this useable in libraries.

### ISSUE THREAD

**Issue by shouse** [for-GET/know-your-http-well#58]
This JSON could generate the documentation / readme.  Thoughts?  I'm searching for code like this and if I don't find something similar, I might take a stab at this.

**Comment by dret** [comment]
On May 7, 2019, at 17:42, Steven <notifications@github.com> wrote:
> This JSON could generate the documentation / readme. Thoughts? I'm searching for code like this and if I don't find something similar, I might take a stab at this.
> 

maybe http://webconcepts.info/JSON-concepts is something interesting to consider as available JSON.
